### ISSUE TITLE
String indices must be integers

### ISSUE THREAD

**Issue by TaHiCo** [ghosx/tieba#2]
Run python main.py...

2020-07-18 06:22:47,257 - INFO - 开始签到第0个用户
2020-07-18 06:22:47,257 - INFO - 获取tbs开始
2020-07-18 06:22:50,244 - INFO - 获取tbs结束
2020-07-18 06:22:50,245 - INFO - 获取关注的贴吧开始

Traceback (most recent call last):
  File "main.py", line 183, in <module>
    main()
  File "main.py", line 177, in main
    client_sign(i, tbs, j["id"], j["name"])

TypeError: string indices must be integers

##[error]Process completed with exit code 1.

**Comment by Z-fly** [comment]
是你在本地运行还是通过Actions运行？

**Comment by ghosx** [comment]
检查下bduss是否复制完全了
