### ISSUE TITLE
请教这个是怎么回事?

### ISSUE THREAD

**Issue by laozhou1204** [ghosx/tieba#3]
2020-07-18 22:15:56,592 - INFO - 开始签到第0个用户
2020-07-18 22:15:56,593 - INFO - 获取tbs开始
2020-07-18 22:15:57,229 - INFO - 获取tbs结束
2020-07-18 22:15:57,229 - INFO - 获取关注的贴吧开始
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    main()
  File "main.py", line 177, in main
    client_sign(i, tbs, j["id"], j["name"])
TypeError: string indices must be integers
##[error]Process completed with exit code 1.

**Comment by laozhou1204** [comment]
![QQ202007210138191792b60bcf815fe7.png](https://www.helloimg.com/images/2020/07/21/QQ202007210138191792b60bcf815fe7.png)

**Comment by ghosx** [comment]
重新获取下bduss试试吧
